tap "adoptopenjdk/openjdk"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "exa"
brew "fzf"
brew "git-flow", link: false
brew "git-flow-avh"
brew "kubernetes-cli"
brew "mas"
brew "minikube"
brew "navi"
brew "node"
brew "sbt"
brew "tldr"
brew "watchman"
brew "yarn"
cask "adoptopenjdk"
cask "adoptopenjdk8"
cask "java"
mas "Bitwarden", id: 1352778147
mas "iHosts", id: 1102004240
mas "Keynote", id: 409183694
mas "Monosnap", id: 540348655
mas "Slack", id: 803453959
mas "Telegram Lite", id: 946399090
mas "WhatsApp", id: 1147396723
